name: unithub
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6
  bottom_navbar_with_indicator: ^0.0.9
  firebase_core: ^3.5.0
  flutter_svg: ^2.0.10+1
  build_runner: ^2.4.11
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_auth: ^5.3.1
  get_it: ^8.0.0
  shared_preferences: ^2.3.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  toastification: ^2.3.0
  brasil_fields: ^1.15.0
  balloon_widget: ^0.0.1+1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  path: ^1.9.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  intl: ^0.19.0
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.7.0
  freezed: ^2.5.2

flutter:

  uses-material-design: true

  assets:
    - assets/